import Footer from "@/components/Footer";
import Header from "@/components/Header";
import clsx from "clsx";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-900 text-slate-100">
      <body className={clsx(urbanist.className, "relative min-h-screen")}>
        <Header/>
        {children}
    
        <Footer/>
        <div className="absolute inset-0 -z-50 max-h-screen background-gradient"></div>
        
      </body>
    </html>
  );
}
